### ISSUE TITLE
Imperative function doesn't appear to work

### ISSUE THREAD

**Issue by AdrianBinDC** [ijoshsmith/break-a-dollar#1]
After the initial `return` for this for the first element, I get an index out of bounds error. Looks like the slice gets passed, though.

**Comment by ijoshsmith** [comment]
Thanks for pointing this out. A lot has changed in Swift over the past couple of years! I've updated the project to work with Swift 3 in 5a597e9

**Comment by AdrianBinDC** [comment]
Wow! Thank you for updating it! I was attempting a similar approach to that problem, but I couldn’t quite get there.
